obstacle_range: 0.1
raytrace_range: 0.05

footprint: [[-0.15,-0.15], [0.15,-0.15], [0.15,0.15], [-0.15,0.15]]
footprint_padding: 0

robot_radius: 0.20

transform_tolerance: 2
inflation_radius: 0.2


observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
