controller_list:
  - name: fake_openmanipulator_arm_controller
    joints:
      - id_1
      - id_2
      - id_3
      - id_4
      - id_5
      - id_6
  - name: fake_gripper_controller
    joints:
      - id_7
initial:  # Define initial robot poses.
  - group: openmanipulator_arm
    pose: arm_zero
  - group: gripper
    pose: gripper_open